name: build

on:
  push:
    branches: [ main, apiv4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Restore NuGet packages in .NET Framework sample
      run: nuget restore samples/Elmah.Io.Log4Net.Console/Elmah.Io.Log4Net.Console.csproj

    - name: Install dependencies
      run: dotnet restore

    - name: Check for vulnerable packages
      shell: bash
      run: |
        set -e # This will cause the script to exit on the first error
        OUTPUT=$(dotnet list src/Elmah.Io.AspNetCore.Log4Net/Elmah.Io.AspNetCore.Log4Net.csproj package --vulnerable)
        echo "$OUTPUT"
        if echo "$OUTPUT" | grep -q 'no vulnerable packages'; then
          echo "No vulnerable packages found"
        else
          if echo "$OUTPUT" | grep -q 'vulnerable'; then
            echo "Vulnerable packages found"
            exit 1
          fi
        fi
        OUTPUT=$(dotnet list src/Elmah.Io.Log4Net/Elmah.Io.Log4Net.csproj package --vulnerable)
        echo "$OUTPUT"
        if echo "$OUTPUT" | grep -q 'no vulnerable packages'; then
          echo "No vulnerable packages found"
        else
          if echo "$OUTPUT" | grep -q 'vulnerable'; then
            echo "Vulnerable packages found"
            exit 1
          fi
        fi

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack Elmah.Io.Log4Net
      run: dotnet pack --configuration Release src/Elmah.Io.Log4Net/Elmah.Io.Log4Net.csproj /p:Version=6.0.${{ github.run_number }}-pre

    - name: Pack Elmah.Io.AspNetCore.Log4Net
      run: dotnet pack --configuration Release src/Elmah.Io.AspNetCore.Log4Net/Elmah.Io.AspNetCore.Log4Net.csproj /p:Version=6.0.${{ github.run_number }}-pre

    - name: Install dotnet-validate
      run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.537

    - name: Validate Elmah.Io.Log4Net
      run: dotnet-validate package local src/Elmah.Io.Log4Net/bin/Release/Elmah.Io.Log4Net.6.0.${{ github.run_number }}-pre.nupkg

    - name: Validate Elmah.Io.AspNetCore.Log4Net
      run: dotnet-validate package local src/Elmah.Io.AspNetCore.Log4Net/bin/Release/Elmah.Io.AspNetCore.Log4Net.6.0.${{ github.run_number }}-pre.nupkg

    - name: Push Elmah.Io.Log4Net to nuget.org
      run: dotnet nuget push src/Elmah.Io.Log4Net/bin/Release/Elmah.Io.Log4Net.6.0.${{ github.run_number }}-pre.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}

    - name: Push Elmah.Io.AspNetCore.Log4Net to nuget.org
      run: dotnet nuget push src/Elmah.Io.AspNetCore.Log4Net/bin/Release/Elmah.Io.AspNetCore.Log4Net.6.0.${{ github.run_number }}-pre.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}

    # - name: Refresh Bugster
    #   shell: pwsh
    #   env:
    #     FUNCTION_APP_URL: ${{ secrets.FUNCTION_APP_URL }}
    #   run: |
    #     $repoName = ($env:GITHUB_REPOSITORY -split '/')[1]
    #     $json = @{ repository = 'Elmah.Io.Log4Net' } | ConvertTo-Json -Compress
    #     curl --fail-with-body -X POST `
    #          -H "Content-Type: application/json" `
    #          -d "$json" `
    #          $env:FUNCTION_APP_URL
    #   if: ${{ github.event_name == 'push' }}